project:
  type: website
  output-dir: docs
  resources:
    - results

website:
  title: "Проект Д.К. Калинская"
  navbar:
    left:
      - href: index.qmd
        text: Главная
      - href: analysis.qmd
        text: Исследование
      - href: notebooks/percy_network_analysis.ipynb
        text: Код
  page-footer:
    center: "Учебный проект по Digital Humanities"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    smooth-scroll: true

bibliography: references.bib
execute:
  freeze: auto
